### ISSUE TITLE
SOCKS_PROXY_HOST和SOCKS_PROXY_PORT 应该填什么？

### ISSUE THREAD

**Issue by MrFutureV** [coderprepares/chatgpt_srt_translator#1]
不会代码的小白，输了指令以后是这样报错
![QQ截图20230415190546](https://user-images.githubusercontent.com/46783891/232210240-e181380c-1d01-4ed5-bfb2-628738d877ff.png)
所以应该是host和端口没写对，还是我没有gpt4的api的原因呢？
然后就是希望能做一个图形的release会容易上手一些

**Comment by coderprepares** [comment]
国内无法直接访问api.openai.com 需要用代理 这里输入的就是本地代理的socks地址和端口
目前的程序还是一个初步的尝试 后续会考虑更新用户界面 和支持api2d接口
只是最近一个月比较忙暂时没空更新这个项目

**Comment by MrFutureV** [comment]
> 国内无法直接访问api.openai.com 需要用代理 这里输入的就是本地代理的socks地址和端口 目前的程序还是一个初步的尝试 后续会考虑更新用户界面 和支持api2d接口 只是最近一个月比较忙暂时没空更新这个项目

好的理解，有问题我自己再琢磨一下吧，感谢提供这样的实用工具，有空再更新就好了

**Comment by MrFutureV** [comment]
> 国内无法直接访问api.openai.com 需要用代理 这里输入的就是本地代理的socks地址和端口 目前的程序还是一个初步的尝试 后续会考虑更新用户界面 和支持api2d接口 只是最近一个月比较忙暂时没空更新这个项目

最近会有时间更新这个项目嘛？

**Comment by coderprepares** [comment]
最近没有啥需要翻译的字幕文件了 所以一直没有更新
你这边主要用来翻译什么字幕呢 可以提供一个字幕文件 后续我可以用来测试
