### ISSUE TITLE
关于已经在src文件夹下置入字幕文件却显示 ENOENT: no such file or directory, scandir './src'

### ISSUE THREAD

**Issue by realogisosetsuna** [coderprepares/chatgpt_srt_translator#2]
<img width="728" alt="image" src="https://github.com/coderprepares/chatgpt_srt_translator/assets/62788759/26e80d9d-ee16-457f-a26b-c275474b0b6b">

**Comment by realogisosetsuna** [comment]
第一次用js，还有很多操作没整明白，还请多多见谅（（

**Comment by coderprepares** [comment]
项目已更新 可以再试一下
